services:
  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  event-store:
    container_name: event-store
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=matcha@latte
      - POSTGRES_USER=matcha_latte
      - POSTGRES_DB=matcha_latte_db
    volumes:
      - ./postgres/event-store.sql:/docker-entrypoint-initdb.d/init.sql

  account-storage:
    container_name: account-storage
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=matcha@latte
      - POSTGRES_USER=matcha_latte
      - POSTGRES_DB=matcha_latte_db
    volumes:
      - ./postgres/account_storage.sql:/docker-entrypoint-initdb.d/init.sql

  storage:
    container_name: storage
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: matcha_latte
      MONGO_INITDB_ROOT_PASSWORD: matcha@latte
      MONGO_INITDB_DATABASEL: matcha_latte_db
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
